package IPInfo;

/*
 * IPInfo.java
 *
 * Created on May 14, 2011, 12:24:06 PM
 */



import java.awt.Component;
import javax.swing.JOptionPane;
import java.util.StringTokenizer;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLConnection;
import static javax.swing.UIManager.*;

/**
 *
 * @author nix0w3i
 */
public class IPInfo extends javax.swing.JFrame {

    /** Creates new form IPLocator */
    public IPInfo() {
        try{
            setLookAndFeel (getSystemLookAndFeelClassName ());
        }catch(Exception e){}
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IP Info v0.1 by nix0w3i");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12));
        jLabel1.setText("Enter IP :");

        jTextField1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 11));

        jLabel2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12));
        jLabel2.setText("Country :");

        jButton1.setText("Go !");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12));
        jLabel3.setText("-");

        jLabel4.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12));
        jLabel4.setText("State :");

        jLabel5.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12));
        jLabel5.setText("-");

        jLabel6.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12));
        jLabel6.setText("City :");

        jLabel7.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12));
        jLabel7.setText("-");

        jLabel8.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12));
        jLabel8.setText("Latitude :");

        jLabel9.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12));
        jLabel9.setText("-");

        jLabel10.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12));
        jLabel10.setText("Longitude :");

        jLabel11.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12));
        jLabel11.setText("-");

        jLabel12.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12));
        jLabel12.setText("Timezone :");

        jLabel13.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12));
        jLabel13.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String ip = jTextField1.getText();
        String info;
        String api_key = "0661da511418add37fd168c89b52ddc51dce08b7fc65d43f3236811c2807ebc4";
        String str_url = "http://api.ipinfodb.com/v3/ip-city/?key=" + api_key + "&ip=" + ip;

        try
        {
            URL url = new URL(str_url);
            URLConnection urlc = url.openConnection();
            BufferedReader br = new BufferedReader(new InputStreamReader(urlc.getInputStream()));
            info = br.readLine();
            StringTokenizer st = new StringTokenizer(info,";");
            if(st.countTokens() == 10)
            {
            String[] final_info = new String[st.countTokens()];
            for(int i = 0;st.hasMoreTokens();i++){
                final_info[i] = st.nextToken();
            }
            jLabel3.setText(final_info[3]);
            jLabel5.setText(final_info[4]);
            jLabel7.setText(final_info[5]);
            jLabel9.setText(final_info[7]);
            jLabel11.setText(final_info[8]);
            jLabel13.setText(final_info[9]);
            }
            else{
                JOptionPane.showConfirmDialog((Component)null, "Invalid IP Address...!", "Alert !", JOptionPane.DEFAULT_OPTION);
            }
        }
        catch(Exception ex){
            JOptionPane.showConfirmDialog((Component)null, "Connection Problem...!", "Error !", JOptionPane.DEFAULT_OPTION);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IPInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
